### PR TITLE
added cpi to packs for CAPV

### PR DESCRIPTION
**Pull request by 3pings**
Added CPI components for Netapp Trident

### CODE REVIEW

**Comment by Sheldonwl** [comment]
Hi @3pings, since you've changed files and added a manifest to the templates folder, won't we need to create a new .tgz as well, with those contents in the archive? Also, will the VSPHERE_VCENTER env always be there for vmware clusters? or does the user have to set that?

**Comment by Sheldonwl** [comment]
@brathina-spectro I can see the changes when pushing it to my own local pack repo, so that yaml seems fine, but when I try to deploy the pack (knowing I don't have the storage backend), the operator won't deploy. Getting this error: 

```
0/1 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane:  │
│ }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling..
```

I can also only test this with an infra pack, since this hasn't been added to the -addon pack, is that supposed to be that way? 

Perhaps I'm getting the error because I don't actually have any netapp storage, but then I would expect a different error, perhaps.

**Comment by brathina-spectro** [comment]
> @brathina-spectro I can see the changes when pushing it to my own local pack repo, so that yaml seems fine, but when I try to deploy the pack (knowing I don't have the storage backend), the operator won't deploy. Getting this error:
> 
> ```
> 0/1 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane:  │
> │ }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling..
> ```
> 
> I can also only test this with an infra pack, since this hasn't been added to the -addon pack, is that supposed to be that way?
> 
> Perhaps I'm getting the error because I don't actually have any netapp storage, but then I would expect a different error, perhaps.

From the error it looks like the pack got deployed, but the pod isn't coming up because of not meeting the scheduling constraints (not enough nodes where the pod can be scheduled). 

This CPI is not needed for the trident addon packs because, its assumed that a different csi (like vsphere-csi or portworx ) will be used as the primary CSI which will have CPI included already. And trident addon will be the secondary CSI in the cluster. Note that, we're adding the CPI for the initial nodes to bootstrap and form the cluster.

**Comment by Sheldonwl** [comment]
@brathina-spectro I only had one master and one worker, but the error states that 0/1 have been deployed, so not sure that the node count is the issue. I don't have the hardware to test it further anyway, so happy to sign-off if you have tested this in the correct env and have it working 👍🏽

**Review by Sheldonwl — APPROVED** [review]

**Pull request merged**
